# Build stage
FROM golang:1.16 AS builder
WORKDIR /src
COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 BOT_ENV=prod go build -o /app .

# Runtime stage
FROM scratch
COPY --from=builder /app /app
VOLUME /data
ENTRYPOINT ["/app"]
