# Build stage
FROM golang:1.16 AS builder
WORKDIR /src
COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build -o /app ./src

# Runtime stage
FROM scratch
COPY --from=builder /app /app
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
VOLUME /data
ENV BOT_ENV=prod
ENTRYPOINT ["/app"]
