version: '3'
services:
  mongodb:
    container_name: mongodb
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
    networks:
      - telebot-network

  telebot:
    image: hungddoo/telebot:latest
    depends_on:
      - mongodb
    volumes:
      - telebot-data:/data
    networks:
      - telebot-network

networks:
  telebot-network:

volumes:
  telebot-data:
  mongo-data: